Code/DesExSearch/config/routes.rb
DesignExchange::Application.routes.draw do

  resources :companies do 
    resources :contacts
  end

  

  resources :tags
  resources :method_case_studies
  root "application#index"

  resources :case_studies do
    collection do 
      get "related_methods", to: "case_studies#related_methods"
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
    member do 
      get "related_methods", to: "case_studies#related_methods", :as => "related_methods"
    end
  end
  resources :design_methods do
    get :autocomplete, on: :collection
    collection do 
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
  end

  resources :discussions do
    collection do 
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
  end

  resources :set do
    collection do
      get "search/:query", to: "application#search", :as => "search"
      get "search", to: "application#search"
      get "test"
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

 

  

  resources :method_categories, only: [:show]
  resources :citations, only: [:show]

  resources :users do
    resources :design_methods, only: [:index]
  end

  get 'search/(:query)', controller: 'design_methods', action: 'search', as: 'search'

  get ":action", to:"application##{:action}"

end

Code/DesExSearch/app/views/layouts/_deheader.html.erb
<style>
  @import url(http://fonts.googleapis.com/css?family=Arvo:700);

  .header-font{
    font-family: 'Arvo', serif;
  }
</style>

<div class="jumbotron">
  <div class="container">
    <div class="row">
  		<div class="col-md-8">
  			<h1 class="header-font">
          <%= image_tag "logo2.png"%>
        </h1>
  			<p class="subtitle">where designers and researchers share methods and best practices</p>
  			</br>
  			<p>Search</p>
  			<form  id="search" role="search">
          	<input type="text" class="form-search" placeholder="Search">
        		<button type="submit" class="btn btn-default" onclick="window.location.href = '<%= search_design_methods_path %>/'+ $('form input.form-search').val();">Submit</button>
      	</form>
  		</div>

      <% if !user_signed_in? %>
      		<div class="col-md-4"><p>Sign In</p>
        		<%= form_for(:user, :url => {:controller => 'devise/sessions', :action => 'new'}) do |f| %>
               <div class="input">
                <%= f.email_field :email, {:autofocus => true, :placeholder => "Username", :class => "form-control"} %>
      			   </div>
      			   </br>
      			   <div class="input">
                  <%= f.password_field :password, {:placeholder => "Password", :class => "form-control"} %>
      			   </div>
               <hr>
      			   <div class="row">
       				   <div class="col-md-8"><%= link_to "Create an account", new_registration_path(:user) %></div>
        				    <div class="col-md-4">
                      <%= f.submit "Log In", {:class=> "btn btn-default pull-right" } %>
                  </div>
      			   </div>
          <% end %>
      		</div>
      <% end %> 

	  </div>
  </div>
</div>
<script type="text/javascript">
$(function(){
  var cache = {};

  $("form#search input").autocomplete(DE.Autocomplete);
});
</script>

Code/DesExSearch/app/views/layouts/_discussion_content.html.erb
<div class='row no-margin-left no-margin-right'>
	<div class='col-md-1'>
    <!-- LIKES SHOULD BE ADDED HERE -->
		<h2 align='center'>-</h2>
		<p align='center'>likes</p>
	</div>
  <div class='col-md-11'>
  	<h4>
      <a class='font-discussion-tittle'> <%= link_to @discussion.title , discussion_path(@discussion.id) %> </a>
    </h4>
      <%= distance_of_time_in_words_to_now(@discussion.created_at)%> ago 
      <%= link_to @discussion.user.email, user_path(@discussion.user_id) %>
      <!-- RESPONSES SHOULD BE ADDED HERE -->
  		<p>- response</p>
      <p>
        <!-- TAGS SHOULD BE ADDED HERE -->
        <% tagifier([]).each do |category| %>
          <span class="tag-label label-gap"> <%= "#{category}" %> </span>
        <% end %>
      </p>
  </div>
  <div class='col-md-12'>
  	<hr>
  </div>
</div>

Code/DesExSearch/app/views/layouts/_footer.html.erb
<div class="inner">
  <ul>
    <li>
      <%= link_to 'About', '/about' %>
    </li>
    <li>
      <%= link_to 'Contact', '/contact' %>
    </li>
  </ul>
</div>

Code/DesExSearch/app/views/layouts/_google.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58344156-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>

Code/DesExSearch/app/views/layouts/_header.html.erb
<div class="inner">
  <%= link_to "DX", root_url, class: "logo" %>
  <%= form_tag "/search", method: "get" do %>
    <%= text_field_tag :query, nil, class: "search_bar", placeholder: "Search for design methods" %>
  <% end %>
  <ul>
    <% if current_user %>
      <li>
        <%= link_to 'All Methods', design_methods_path %>
      </li>
      <li>
        <%= link_to 'My Profile', current_user %>
      </li>
      <li>
        <%= link_to "Sign Out", destroy_user_session_url, method: "delete" %>
      </li>
    <% else %>
      <li>
        <%= link_to 'All Methods', design_methods_path %>
      </li>
      <li>
        <%= link_to "Sign in", new_user_session_url %>
      </li>
    <% end %>
  </ul>
</div>

Code/DesExSearch/app/views/layouts/_headernav.html.erb
<script type="text/javascript">
  $(function(){
    $('form#search input').autocomplete(DE.Autocomplete);
  });
</script>
 <nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag "logo-DE.png", :width => "100", :id => "logo" %>
      </a>
    </div>
    <form id="search" class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default" onclick="window.location.href = '<%= search_design_methods_path %>/'+ $('form#search input').val();">Search</button>
      </form>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Methods", design_methods_path %></li>
        <li><%= link_to "Case Studies", case_studies_path %></li>
        <li><%= link_to "Discussions", discussions_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Sets", set_index_path %></li>
              <li><%= link_to "Account Information", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

Code/DesExSearch/app/views/layouts/_sidebar.html.erb
<script type="text/javascript">
$(function(){
  enableAccordion();
});
function enableAccordion(){
  $('.category').find('.category-heading')
             .click(function(){ 
              var content = $(this).siblings();
              content.toggleClass('in');
            })
}
</script>

<style>
  .sidebar-element{
    padding-left: 10px;
  }

  .sidebar-leaf{
  	font-weight: normal;
  	display: block;
  }

  .sidebar-maincategory{
  	font-weight: bold;
  }
</style>

<%= print_children(0,@category_hash).html_safe %>

Code/DesExSearch/app/views/layouts/_thumbnail.html.erb
<!-- STYLE at APPLICATION.CSS ... THUMBNAIL CSS -->
<div class= "<%= "col-sm-6 col-md-#{@thumb_obj[:col_md_value]} left-top-padding" %>" >
  <div class="thumbnail search-item">
  	<div class="caption">
  		<h5> 
        <%= link_to "#{@thumb_obj[:name]}", eval("#{@thumb_obj[:link]}_path(#{@thumb_obj[:id]})") %> 
      </h5>
      <% if @thumb_obj[:image].present?  %>
        <div class="image-wrapper">
         <%= image_tag @thumb_obj[:image]%>
        </div>
      <% end  %>
      <p class="likes">
        <span class="glyphicon glyphicon-star"></span> 
        <% "#{@thumb_obj[:likes]}" %>  <% "#{@thumb_obj[:likes]}" %><%= rand(100)%> Likes
      </p>
  		<p class="truncate-multiline"> 
        <%= "#{@thumb_obj[:description][0..@thumb_obj[:word_count]]}" %>
        <%= link_to "[...]", eval("#{@thumb_obj[:link]}_path(#{@thumb_obj[:id]})") %>
      </p> 
      <p>
        <% tagifier(@thumb_obj[:tags]).each do |category| %>
          <span class="tag-label label-gap"> <%= "#{category}" %> </span>
        <% end %>
      </p>
  	</div>
  </div>
</div>

Code/DesExSearch/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DesignExchange</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    params[:controller], :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render "layouts/google" %>
</head>
<body>

<!-- <header>
  <%= render "layouts/header" %>
</header> 
 -->
<!-- <div class="content"> -->
<!--   <ul>
    <% flash.each do |type, message| %>
      <li class="flash flash-<%= type %>"><%= message %></li>
    <% end %>
  </ul> -->

  <%= yield %>
<!-- </div> -->

<!-- <footer>
  <%= render "layouts/footer" %>
</footer> -->

</body>
</html>

Code/DesExSearch/app/views/layouts/custom.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "DEx - #{params[:controller].camelize}" %> </title>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    params[:controller], :media => "all" %>
  <%= csrf_meta_tags %>
  <%= render "layouts/google" %>
  <script> 

    $(function(){
      $('button').click(function(e){
        e.preventDefault();
      });
    })
  </script>

  <style>

  .jumbotron{
    font-size: 17px;
    background: rgb(89, 88, 91);
    color: white;
  }
  .subtitle{
    font-size: 20px;
  }

  .login-margin{
    margin-left: 25%;
    margin-right: 25%;
    margin-top: 5%;
  }
  footer{
    height: 100px;
  }
  </style>
</head>
<body>



  <%= render "layouts/headernav" %>
  <!-- Header for the application#index view -->
  <% if params[:controller] == "application" and params[:action] == "index" %>
    <%= render "layouts/deheader" %>
  <% end %>
  <!-- End of header for application#index -->

  <div class="container">
  	 <%= yield %>
  </div>
  <footer>
  </footer>
</body>
</html>

Code/DesExSearch/app/views/layouts/wide.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "DEx - #{params[:controller].camelize}" %> </title>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= render "layouts/google" %>
  <script> 
    $(function(){
      $('button').click(function(e){
        e.preventDefault();
      });
    })


  </script>
  <style>

    .nav-bar-margin{
      padding-left: 20px;
      margin-right: 20px;
      margin-left: 10px;
    }

    .font-discussion-tittle{
      margin-top: 20px;
      margin-bottom: 10px;
      font-size: 30px;

    }

  </style>
</head>
<body>


<%= render "layouts/headernav" %>
   <%= yield %>
</body>
</html>