Code/DesExSearch/config/routes.rb
DesignExchange::Application.routes.draw do

  resources :companies do 
    resources :contacts
  end

  

  resources :tags
  resources :method_case_studies
  root "application#index"

  resources :case_studies do
    collection do 
      get "related_methods", to: "case_studies#related_methods"
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
    member do 
      get "related_methods", to: "case_studies#related_methods", :as => "related_methods"
    end
  end
  resources :design_methods do
    get :autocomplete, on: :collection
    collection do 
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
  end

  resources :discussions do
    collection do 
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
  end

  resources :set do
    collection do
      get "search/:query", to: "application#search", :as => "search"
      get "search", to: "application#search"
      get "test"
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

 

  

  resources :method_categories, only: [:show]
  resources :citations, only: [:show]

  resources :users do
    resources :design_methods, only: [:index]
  end

  get 'search/(:query)', controller: 'design_methods', action: 'search', as: 'search'

  get ":action", to:"application##{:action}"

end

Code/DesExSearch/app/models/contact.rb
class Contact < ActiveRecord::Base
	attr_accessible :name, :email, :phone, :company_id
	has_many :case_studies
	belongs_to :company
	validates_presence_of :name, :email

	before_save { self.email = email.downcase }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

end

Code/DesExSearch/app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base
	layout "custom"
	def new 
		@company = Company.find(params[:company_id])
		@contact = Contact.new(:company_id => @company.id)
	end
end

Code/DesExSearch/app/helpers/contacts_helper.rb
module ContactsHelper
end

Code/DesExSearch/app/views/contacts/_form.html.erb
<%= form_for([@company, @contact]) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= select("contact", "company_id", Company.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'None'}, :class => "form-control")%>
  </div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Code/DesExSearch/app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

Code/DesExSearch/app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Company</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.company.name %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

Code/DesExSearch/app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', company_contacts_path %>

Code/DesExSearch/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contact.company.name %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>