Code/DesExSearch/config/routes.rb
DesignExchange::Application.routes.draw do

  resources :companies do 
    resources :contacts
  end

  

  resources :tags
  resources :method_case_studies
  root "application#index"

  resources :case_studies do
    collection do 
      get "related_methods", to: "case_studies#related_methods"
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
    member do 
      get "related_methods", to: "case_studies#related_methods", :as => "related_methods"
    end
  end
  resources :design_methods do
    get :autocomplete, on: :collection
    collection do 
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
  end

  resources :discussions do
    collection do 
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
  end

  resources :set do
    collection do
      get "search/:query", to: "application#search", :as => "search"
      get "search", to: "application#search"
      get "test"
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

 

  

  resources :method_categories, only: [:show]
  resources :citations, only: [:show]

  resources :users do
    resources :design_methods, only: [:index]
  end

  get 'search/(:query)', controller: 'design_methods', action: 'search', as: 'search'

  get ":action", to:"application##{:action}"

end

Code/DesExSearch/app/models/tag.rb
class Tag < ActiveRecord::Base
	attr_accessible :design_method_id, :case_study_id, :discussion_id, :user_id, :content, :content_type
	belongs_to :design_method
	belongs_to :case_study
	belongs_to :discussion
	belongs_to :user
	before_save { self.content = content.downcase.gsub(' ', '_') }
	validates :content, :uniqueness => { :scope => [ "case_study_id", "design_method_id", "discussion_id", "content_type"]}
end

Code/DesExSearch/app/controllers/tags_controller.rb
class TagsController < InheritedResources::Base
	def create
    @tag = Tag.new(params[:tag])

   
      if @tag.save
        # format.html { redirect_to @tag, notice: 'Design method was successfully created.' }
        # format.json { render json: @tag, status: :created, location: @tag }
        render :json => {:tag => tagify(@tag.id, @tag.content, {:removable => true})}
      else
        render json: @tag.errors, status: :unprocessable_entity
      end
    
  end
  def tagify(id, content, options)
    tag = "<span class='tag-label label-gap'>#{content}  " 
      if options[:removable]
        tag = tag + '<span onclick="removeTag('+ (id.to_s) +', this);" class="glyphicon glyphicon-remove-circle"></span>' 
      end
      tag = tag + '</span>'
    tag.html_safe
  end
end

Code/DesExSearch/app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :design_method_id %><br>
    <%= f.number_field :design_method_id %>
  </div>
  <div class="field">
    <%= f.label :case_study_id %><br>
    <%= f.number_field :case_study_id %>
  </div>
  <div class="field">
    <%= f.label :discussion_id %><br>
    <%= f.number_field :discussion_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Code/DesExSearch/app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

Code/DesExSearch/app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th>Design method</th>
      <th>Case study</th>
      <th>Discussion</th>
      <th>User</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.design_method_id %></td>
        <td><%= tag.case_study_id %></td>
        <td><%= tag.discussion_id %></td>
        <td><%= tag.user_id %></td>
        <td><%= tag.content %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

Code/DesExSearch/app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

Code/DesExSearch/app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Design method:</strong>
  <%= @tag.design_method_id %>
</p>

<p>
  <strong>Case study:</strong>
  <%= @tag.case_study_id %>
</p>

<p>
  <strong>Discussion:</strong>
  <%= @tag.discussion_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @tag.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tag.content %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>