Code/DesExSearch/config/routes.rb
DesignExchange::Application.routes.draw do

  resources :companies do 
    resources :contacts
  end

  

  resources :tags
  resources :method_case_studies
  root "application#index"

  resources :case_studies do
    collection do 
      get "related_methods", to: "case_studies#related_methods"
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
    member do 
      get "related_methods", to: "case_studies#related_methods", :as => "related_methods"
    end
  end
  resources :design_methods do
    get :autocomplete, on: :collection
    collection do 
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
  end

  resources :discussions do
    collection do 
      get "search/:query", to: "application#search"
      get "search", to: "application#search", :as => "search"
    end
  end

  resources :set do
    collection do
      get "search/:query", to: "application#search", :as => "search"
      get "search", to: "application#search"
      get "test"
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

 

  

  resources :method_categories, only: [:show]
  resources :citations, only: [:show]

  resources :users do
    resources :design_methods, only: [:index]
  end

  get 'search/(:query)', controller: 'design_methods', action: 'search', as: 'search'

  get ":action", to:"application##{:action}"

end

Code/DesExSearch/app/models/design_method.rb
# == Schema Information
#
# Table name: design_methods
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  overview   :text             not null
#  process    :text             not null
#  principle  :text             not null
#  owner_id   :integer          not null
#  parent_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class DesignMethod < ActiveRecord::Base
  mount_uploader :main_image, PictureUploader
  attr_accessible :name, :process, :num_of_designers, :num_of_users, :overview, :main_image, :time_period, :name, :time_unit
  validates :name, :overview, presence: true
  validates :name, length: { maximum: 255,
            too_long: "%{count} is the maximum character length."}
  validates :name, uniqueness: { case_sensitive: false,
            message: "Already exists. Try editing an existing one."},
            on: :create
  validates :owner_id, presence: true

  searchable do
    text :name, stored: true
    text :overview, stored: true
    text :principle, stored: true
    text :process, stored: true
    text :method_categories do
      method_categories.map { |method_category| method_category.name }
    end
  end

  def overview
    if self[:overview] == "default"
      self[:overview] = "No overview available"
    end
    return self[:overview]
  end

  def process
    if self[:process] == "default"
      self[:process] = "No process available"
    end
    return self[:process]
  end

  def tags
        Tag.where("design_method_id = ? and content_type = ?", self[:id], "tag");
  end

  def tools
      Tag.where("design_method_id = ? and content_type = ?", self[:id], "tool");
  end

  class Document_Attach < Document
    attr_reader :obj

    def initialize(obj)
        if obj.is_a?(DesignMethod)
          super(:content => obj.overview+" "+obj.process)
        elsif obj.is_a?(CaseStudy)
          super(:content => obj.description)
        end
        @obj = obj
    end
  end

  def similar_methods(limit, sample_size)
    logger.info "Similar Methods running for: #{self[:name]}"
    startTime = Time.now

    methodsList = DesignMethod.where("design_methods.id != ?", self[:id])
    .order("RANDOM()")
    .limit(limit)

    comparator = Corpus.new
    comparingMethod = Document_Attach.new(self)
    comparator << comparingMethod

    methodsList.each do |dm|
      comparator << Document_Attach.new(dm)
    end

    result = comparator.similar_documents(comparingMethod).sort {|tuple1, tuple2| tuple2[1] <=> tuple1[1] }
    result = result.map {|tuple| tuple[0].obj}
    result = result [1..sample_size]

    endTime = Time.now
    elapsed_time = endTime - startTime
    logger.info "Similar Methods took #{elapsed_time}s to query #{limit} random sample from db."
    return result
  end

  def similar_case_studies(limit, sample_size)
    logger.info "Similar Case Studies running for: #{self[:name]}"
    startTime = Time.now

    caseStudiesList = CaseStudy.order("RANDOM()")
    .limit(limit)

    comparator = Corpus.new
    comparingMethod = Document_Attach.new(self)
    comparator << comparingMethod

    caseStudiesList.each do |cs|
      comparator << Document_Attach.new(cs)
    end

    result = comparator.similar_documents(comparingMethod).sort {|tuple1, tuple2| tuple2[1] <=> tuple1[1] }
    result = result.map {|tuple| tuple[0].obj}
    result = result [1..sample_size]

    endTime = Time.now
    elapsed_time = endTime - startTime
    logger.info "Similar Case Studies took #{elapsed_time}s to query #{limit} random sample from db."
    return result
  end

  has_many :categorizations, dependent: :destroy
  has_many :method_categories, through: :categorizations
  has_many :method_citations, dependent: :destroy
  has_many :citations, through: :method_citations
  has_many :method_favorites, dependent: :destroy
  has_many :favorited_users, through: :method_favorites, :source => :user
  belongs_to :owner, class_name: "User", foreign_key: :owner_id

  # CASE STUDY LINKING 
  has_many :method_case_studies
  has_many :case_studies, :through => :method_case_studies

  # Method variations
  has_many :variations, class_name: "DesignMethod", foreign_key: :parent_id
  belongs_to :parent, class_name: "DesignMethod"

  # Comments
  has_many :comments, dependent: :destroy
  has_many :tags
end 

Code/DesExSearch/app/controllers/design_methods_controller.rb
class DesignMethodsController < ApplicationController

  def index
    @design_methods = DesignMethod.where("overview != ?", "No overview available" ).take(24)
    # @design_methods = DesignMethod.take(24)

    render :layout => "wide"
  end

  def new
    @design_method = DesignMethod.new
    render :layout => "custom"
  end

  # Edit an existing DesignMethod
  #
  # === Parameters
  # - id: ID of the design method to be edited
  #
  # === Variables
  # - @design_method: the design method to be edited
  def edit
    @design_method = DesignMethod.find(params[:id])
    render :layout => "custom"
  end


  # Update an existing DesignMethod corresponding to the ID in the URI
  #
  # === Request Body
  # - design_method: a hash containing information to update the DesignMethod with
  #
  # === Variables
  # - @design_method: the updated design method
  def update
    @design_method = DesignMethod.find(params[:id])

    respond_to do |format|
      if @design_method.update_attributes(params[:design_method])
        format.html { redirect_to @design_method, notice: 'Design method was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @design_method.errors, status: :unprocessable_entity }
      end
    end
  end


  # Creates a DesignMethod
  #
  # === Request Body
  # - design_method: a hash containing the required fields for creating a DesignMethod
  #
  # === Variables
  # - @design_method: the newly created design method
  def create
    @design_method = DesignMethod.new(params[:design_method])
    @design_method.owner = current_user
    @design_method.principle = ""

    respond_to do |format|
      if @design_method.save
        format.html { redirect_to @design_method, notice: 'Design method was successfully created.' }
        format.json { render json: @design_method, status: :created, location: @design_method }
      else
        format.html { render action: "new" }
        format.json { render json: @design_method.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    id = params[:id].to_i
    #default to method id #1 TODO remove
    dm = DesignMethod.find(id)
    @method = dm
    @author = dm.owner
    @citations = dm.citations
    @similar_methods = @method.similar_methods(100,6)
    @similar_case_studies = @method.similar_case_studies(100,6)
    render :layout => "custom"
    # render :json => @method.neighbors(100, 6)
  end

  def search
    render :layout => "wide"
  end
end

Code/DesExSearch/app/helpers/design_methods_helper.rb
module DesignMethodsHelper
	def glyphyify(value)
	   content_tag(:span, "", :class => "glyphicon glyphicon-#{value}")
	end
end

Code/DesExSearch/app/views/design_methods/_form.html.erb
<script> 
  $(function(){
    adjustSaveBar();
  });
  
  function adjustSaveBar(){
    var pH = $('#publish-btn').parent().height()
    var eH = $('#publish-btn').height()
    $('#publish-btn').css('margin-top', (pH - eH)/2)

    //pH = $('#save-btn').parent().height()
    eH = $('#save-btn').height()
    $('#save-btn').css('margin-top', (pH - eH)/2)

    pH = $('#auto-saved-text').parent().height()
    eH = $('#auto-saved-text').height()
    $('#auto-saved-text').css('margin-top', (pH - eH)/2)
  }
</script>
<%= form_for @design_method, :html => {:multipart => true} do |f| %>
<!-- ERROR MESSAGES -->
<% if @design_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design_method.errors.count, "error") %> prohibited this design_method from being saved:</h2>

      <ul>
      <% @design_method.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
<!-- INPUT FIELDS -->
<div id="save-bar" class="row">
  <%= f.submit "Publish", :id => "publish-btn", :class => "btn btn-primary pull-right" %>
   
  <button type="button" class="btn btn-default pull-right" id="save-btn" name="commit" type="submit">
    <%= glyphyify("floppy-disk") %> Save as Draft
  </button>
 
  <!-- </button> -->
  <span id="auto-saved-text" class="pull-right">Auto-saved as draft 2 minutes ago</span>
</div>

<!-- BODY -->
<div class = "row">

  <!-- LEFT CONTENT -->
	<div class="col-md-4">

    <!-- PEOPLE -->
		<div class="row">
			<h4>People</h4>
			<div class="input-group">
  				<span class="input-group-addon">
  					<span class="glyphicon glyphicon-user" > collaborators</span>
  				</span>
          <%= f.number_field :num_of_designers, :class => "form-control", :placeholder => "# of collaborators", in: 0...1000 %>
			</div>
      <br>
			<div class="input-group">
  				<span class="input-group-addon">
  					<span class="glyphicon glyphicon-user" > users       </span>
  				</span>
          <%= f.number_field :num_of_users, :class => "form-control", :placeholder => "# of users", in: 0...1000 %>
			</div>
		</div>
    <!-- END PEOPLE -->

    <!-- TOOLS -->
  	<div class="row">
			<h4>Tools</h4>
			<div class="input-group">
  				<span class="input-group-addon">
  					<span class="glyphicon glyphicon-pencil" ></span>
  				</span>
  				<input type="text" class="form-control" placeholder="Ex. paper, pen">
			</div>
		</div>
    <!-- END TOOLS -->

    <!-- TIME -->
  	<div class="row">
			<h4>Time</h4>
			<div class="input-group">
  				<span class="input-group-addon">
  					<span class="glyphicon glyphicon-time" ></span>
  				</span>
  				 <%= f.number_field :time_period, :class => "form-control", in: 0...1000 %>
          <%= f.select(:time_unit, options_for_select([['years', 'yr'], ['days', 'd'], ['hours', 'hr'], ['minutes', 'min']], @design_method.time_unit), {}, {:class=> "form-control"})%>

			</div>
  	</div>
    <!-- END TIME -->

    <!-- TAGS -->
  	<div class="row">
			<h4>Tags</h4>  
      <div class="input-group">
      <input type="text" class="form-control">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button" onclick="createTag('design_method', <%=params[:id]%>, this);">Add Tag</button>
      </span>
    </div>
    <br>
      <p class='tag-list'>
        <% @design_method.tags.each do |t| %>
         <%= tagify(t.id, t.content, {:removable => true}) %>
        <% end %>
      </p>
  	</div>
	</div>
  <!-- END OF TAGS -->
  <!-- END LEFT CONTENT -->

  <!-- RIGHT CONTENT -->
  <div class="col-md-8">
      <!-- INPUT METHOD NAME -->
      <h3>Method Name </h3>
  		<div class="input-group-lg" style="margin-top: 10px;margin-bottom: 10px;">
  		  <%= f.text_field :name, :class=> "form-control", :placeholder => "Method Name" %>
		  </div>
      <!-- END INPUT METHOD NAME -->

      <!-- IMAGES -->
      <div class="row">
        <div class="col-xs-6 col-md-12">
        <% if @design_method.main_image.present? %>
          <%= image_tag(@design_method.main_image)%>
        <% else %>
          <%= image_tag("no-image-available.png", :width => "100%", :height => "385")%>
        <% end %>
        </div>
    
      </div>
      <br/>
      <%= f.file_field :main_image %>
      <!-- END IMAGES -->

      <!-- FORMS -->
      <h3>Summary</h3>
        <%= f.text_area :overview, :class => "form-control", :rows => 6 %>
      
          

      <h3>Process</h3>
      <%= f.text_area :process, :class => "form-control", :rows => 20 %>

      <!-- INPUT FIELDS -->
     

      <!-- END FORMS -->
</div>
<!-- END RIGHT CONTENT -->
</div>
<br>
  <div id="save-bar" class="row">
    <%= f.submit "Publish", :id => "publish-btn", :class => "btn btn-primary pull-right" %>
     
    <button type="button" class="btn btn-default pull-right" id="save-btn" name="commit" type="submit">
      <%= glyphyify("floppy-disk") %> Save as Draft
    </button>
   
    <!-- <span id="auto-saved-text" class="pull-right">Auto-saved as draft 2 minutes ago</span> -->
  </div>
<!-- END BODY -->
<% end %>

Code/DesExSearch/app/views/design_methods/index.html.erb
<script> 
	$(function(){
		var pH = $('#create-btn').parent().parent().height()
		var eH = $('#create-btn').height()
		$('#create-btn').css('margin-top', (pH - eH)/2)
	});
</script>

<div class = "row">
	<div class="col-md-2">

	</div>
  	<div class="col-md-10 left-pad">
	<div class="col-md-6">
		<h3>Popular Methods</h3>
	</div>
  	<div class="col-md-6">
		<button id='create-btn' type="submit" class="btn btn-default pull-right" onclick="window.location.href = '<%= new_design_method_path %>';"><span class="glyphicon glyphicon-plus"></span> Create Method</button>
  	</div>
  	</div>
</div>
<div class = "row">
	<div class="col-md-2">
		<%= render "/layouts/sidebar", locals: @category_hash = sidebar_hash(:methods) %>
	</div>
  	<div class="col-md-10 left-pad">
  		<% @design_methods.each do |method| %>
  		 	<%= render "/layouts/thumbnail", locals: @thumb_obj = thumbnail(method,"3") %>
      	<% end %>
  	</div>
</div>

Code/DesExSearch/app/views/design_methods/search.html.erb
<h1>Methods#search</h1>

<%= link_to "Home", "/de/index" %>
<img src="https://designexchange.mybalsamiq.com/projects/de/Search%20Results%20-%20Methods%20-%20User%20Testing.jpeg?version=19&etag=rWmlofZM.FtT.hS3Rx.bCrqwD7E0u7fw"/>

Code/DesExSearch/app/views/design_methods/show.html.erb
<style>
	.no-padding{
		padding: 0%;
	}
</style>

<!-- Method Name -->
<div class = "row">
	<div class="col-md-9 col-md-offset-3 left-pad">
    <h3><%= @method.name != nil ? @method.name.humanize().split.map(&:capitalize).join(' ') : "-" %></h3>
    <p>By <a href="<%= user_path(@author.id)%>"><%= @author.email != nil ? @author.email : "-" %></a></p>
	</div>

</div>
<!-- End Method Name -->

<div class = "row">
    <!-- SIDEBAR -->
	<div id="sidebar" class="col-md-3">
		<div class = "row">
			<h3>What You'll Need</h3>
		</div>

    <!-- PEOPLE -->
		<div class="row">
			<h4>People</h4>
			<p>
				<span class="glyphicon glyphicon-user"></span>
				~<%= pluralize(@method.num_of_designers, "designer") %> 
			</p>
			<p>
				<span class="glyphicon glyphicon-user"></span>
				~<%= pluralize(@method.num_of_users, "user") %> 
			</p>
		</div>
    <!-- END PEOPLE -->

    <!-- TOOLS -->
  	<div class="row">
			<h4>Tools</h4>
			<p>
				<span class="glyphicon glyphicon-pencil"></span>
				-
			</p>
		</div>
    <!-- END TOOLS -->

    <!-- TIME -->
  	<div class="row">
			<h4>Time</h4>
			<p>
				<span class="glyphicon glyphicon-time"></span>
				<%= pluralize(@method.time_period, @method.time_unit) %> 
			</p>
  	</div>
    <!-- END TIME -->

    <!-- TAGS -->
  	<div class="row">
			<h4>Tags</h4>
      <p>
        <% @method.tags.each do |t| %>
         <%= tagify(t.id, t.content, {:removable => false}) %>
        <% end %>
        <%= "No tags available" unless not @method.tags.empty? %>
      </p>
      <!-- END TAGS -->
  	</div>
	</div>
  	<!-- END SIDBAR -->


    <!-- MAIN VIEW  -->
  	<div class="col-md-9 add-padding">
       	<!-- MENU BAR -->
  		<div class="row">
  			<div class="col-md-3">
  				<span class="glyphicon glyphicon-star"></span>
  				<%= @method.likes %> likes
  			</div>
  			<div class="col-md-3">
          		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          			<span class="glyphicon glyphicon-folder-open"></span>
                Add to Set
          			<b class="caret"></b>
          		</a>
          		<ul class="dropdown-menu">
            		<li><a href="#">Add To Set</a></li>
            		<li class="divider"></li>
            		<li><a href="<%= set_index_path %>">My Favorites</a></li>
          		</ul>
  			</div>
  			<div class="col-md-3">
  				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          				<span class="glyphicon glyphicon-share"></span>
          					Share
          				<b class="caret"></b>
          		</a>
          			<ul class="dropdown-menu">
            			<li><a href="#">Email</a></li>
          			</ul>
  			</div>
  			<div class="col-md-3">
  				<a href= "<%= edit_design_method_path(params[:id]) %>" class="pull-right">
          	<span class="glyphicon glyphicon-pencil">Edit</span>
          </a>
  			</div>
  		</div>
      	<!-- END MENU BAR -->
      <br>
      <!-- CONTENT -->
  		<div class="row">
        <% if @method.main_image.present? %>
          <%= image_tag(@method.main_image, :width => "100%")%>
        <% else %>
          <%= image_tag("no-image-available.png", :width => "100%", :height => "385")%>
        <% end %>
  		</div>
      <br>
  		<!-- OVERVIEW & PROCESS -->
  		<div class="row">
  			<h4> Overview </h4>
        	<%= @method.overview != nil ? simple_format(@method.overview) : "-"%>
        	<h4> Process </h4>
        	<p><%= @method.process != nil ? simple_format(@method.process) : "-" %></p>
    	</div>
    	<!-- END OF OVERVIEW & PROVESS -->

    	<!-- USERS INFORMATION -->

  		<div class="row">
  			<h4> Contributing Authors </h4>
  			<!-- POSSIBLE DO WHILE FOR USERS INFORMATION  -->
  			<div class="col-md-6">
  				<div class="col-md-4">
  					<img alt="" src="http://newsdesk.si.edu/sites/default/files/imagecache/photo_pagewidth/photos/anonymous_silhouette.jpg" class="fit-all"/>
  				</div>
  				<div class="col-md-8">
  					<p><a>Name of person</a></p>
  					<p>Some info</p>
  				</div>
  			</div>
  			<!-- END POSSIBLE DO WHILE FOR USERS INFORMATION  -->
  		</div>
  		<!-- END OF USERS INFORMATIONS -->

  		<!-- DISCUSSION FIELD -->
  		<div class="row">
  			<h4>Discussions</h4>
  			<textarea class="form-control" rows="3" placeholder="Questions or comments about this method?"></textarea>
  			<button type="submit" class="btn btn-default pull-right">Submit</button>
  		</div>
  		<!-- END DISCUSSION FIELD -->

  		<!-- DISCUSSIONS -->
  		<div class="row">
  			<!-- !!! PROBABLY A DO WHILE HERE TO LOAD DISCUSSIONS !!! -->
  			<hr>
  			<div class="col-md-3">
  				<div class="row">
  					<div class="col-md-5 no-padding">
  						<img alt="" src="http://newsdesk.si.edu/sites/default/files/imagecache/photo_pagewidth/photos/anonymous_silhouette.jpg" class="fit-all"/>
  					</div>
  					<div class="col-md-7">
  						<a href="#">
          					Example of a Name
          				</a>
          				<p>
          					Example of City
          				</p>
  					</div>
  				</div>
  				<a href="#">
          			<span class="glyphicon glyphicon-share"></span>
          				Share
          		</a>
          		<br>
          		<a href="#">
          			<span class="glyphicon glyphicon-comment"></span>
          				Message
          		</a>
          		<br>
          		<a href="#">
          			<span class="glyphicon glyphicon-heart"></span>
          				Follow
          		</a>
          	</div>
  			<div class="col-md-9 no-padding">
  				<p>
  					Date
  				</p>
  				<p>
  					Message
  				</p>
  			</div>
  			<div class="row">
  				<div class="col-md-9 col-md-offset-3">
  					<button type="submit" class="btn btn-default">Useful (#)</button>
  					<button type="submit" class="btn btn-default">Interesting (#)</button>
  					<button type="submit" class="btn btn-default pull-right">Reply</button>
  				</div>
  			</div>
  			<!-- END OF POSSIBLE DO WHILE -->
	
  			<!-- LOAD MORE DISCUSSIONS -->
  			<hr>
  				<div style="text-align: center;">
  				<a href="#">
         	 		See More Discussions <b class="caret"></b>
        	  	</a>
        	  </div>
  			<hr>
  			<!-- END LOAD MORE DISCUSSIONS -->
  		</div>

  		<!-- RELATED METHODS AND CASE STUDIES -->
  		<div class="row">
        <!-- RELATED METHODS -->
  			<h4>Related Methods</h4>
          <% @similar_methods.each do |dm| %>
            <%= render "/layouts/thumbnail", locals: @thumb_obj = thumbnail(dm,"4") %>
          <% end %>
  			<!-- END RELATED METHODS -->

        <!-- RELATED CASE STUDIES -->
  			<h4>Related Case Studies</h4>
          <% @similar_case_studies.each do |cs| %>
            <%= render "/layouts/thumbnail", locals: @thumb_obj = thumbnail(cs,"4") %>
          <% end %>
  			<!-- ENF RELATED CASE STUDIES -->
  		</div>
  		<!-- END RELATED METHODS AND CASE STUDIES -->

  		<!-- CITATIONS -->
  		<h4>Citations</h4>
      <% if @citations.length != 0 && @citations != nil %>
          <ol> 
          	<% @citations.each do |c| %>
          		<li><%= c.text %></li>
          	<% end %> 
          </ol>
      <% else %>
        No citations available. 
      <% end %>
        <!-- END CITATIONS -->

        <!-- END CONTENT -->
  	</div>
  	<!-- END MAIN VIEW -->
</div>